name: Build And Upload Image
on:
  push:
    branches:
      - 'ci/feat/*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: Extract Image Tag
        run: |
          BRANCH_NAME=$(echo "${{ github.ref }}" | sed 's|refs/heads/ci/||; s|/|-|g' | tr '[:upper:]' '[:lower:]')
          DATE=$(date +%d%m%y) # 获取当前日期格式为DDMMYY
          echo "IMAGE_TAG=${BRANCH_NAME}_${DATE}" >> $GITHUB_ENV
      - name: Extract Version and Commit ID
        run: |
          echo VERSION=test >> $GITHUB_ENV
          echo COMMIT_ID=${GITHUB_SHA:0:7} >> $GITHUB_ENV
      - name: Build and Push Image
        uses: docker/build-push-action@v6 
        with:
          push: true
          context: .
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ${{ secrets.DOCKER_USER_NAME }}/moments:${{ env.IMAGE_TAG }}
          build-args: |
            VERSION=${{ env.VERSION }}
            COMMIT_ID=${{ env.COMMIT_ID }}
